version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./data:/var/www/html/data
    env_file:
      - .env.docker
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=${APP_URL:-http://localhost:8080}
      - DB_CONNECTION=${DB_CONNECTION:-sqlite}
      - DB_DATABASE=${DB_DATABASE:-/var/www/html/data/database.sqlite}
    restart: unless-stopped

volumes:
  data:
    driver: local
